import { createSlice, PayloadAction } from "@reduxjs/toolkit";
export interface Column {
  id: string;
  name: string;
  cards: CardI[];
}
export interface CardI {
  name: string;
  idList: string;
  id: string;
  subTasks: string[];
}

export interface ColumnsState {
  columns: Column[];
  loading: boolean;
}

const initialState: ColumnsState = {
  columns: [],
  loading: true,
};

export const columnSlice = createSlice({
  name: "columns",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setColumns: (state, { payload }: PayloadAction<Column[]>) => {
      state.columns = payload;
    },
    createTaskAction: (state, { payload }: PayloadAction<CardI>) => {
      const columnIndex = state.columns.findIndex(
        (col) => col.id === payload.idList
      );
      state.columns[columnIndex].cards.push(payload);
    },
    updateTaskAction: (
      state,
      { payload }: PayloadAction<{ card: CardI; id: string }>
    ) => {
      const columnIndex = state.columns.findIndex(
        (col) => col.id === payload.card.idList
      );
      const taskIndex = state.columns[columnIndex].cards.findIndex(
        (card) => card.id === payload.id
      );
      state.columns[columnIndex].cards.splice(taskIndex, 1, payload.card);
    },
    removeTaskAction: (
      state,
      { payload }: PayloadAction<{ idList: string; id: string }>
    ) => {
      const columnIndex = state.columns.findIndex(
        (col) => col.id === payload.idList
      );

      const taskIndex = state.columns[columnIndex].cards.findIndex(
        (card) => card.id === payload.id
      );
      state.columns[columnIndex].cards.splice(taskIndex, 1);
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
});

export const {
  setColumns,
  updateTaskAction,
  createTaskAction,
  removeTaskAction,
} = columnSlice.actions;

export default columnSlice.reducer;
